# Generated by Django 3.1.1 on 2020-11-15 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201114_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user',
            name='Followers',
        ),
        migrations.AddField(
            model_name='user',
            name='Followers',
            field=models.ManyToManyField(default=0, related_name='_user_Followers_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user',
            name='Following',
        ),
        migrations.AddField(
            model_name='user',
            name='Following',
            field=models.ManyToManyField(default=0, related_name='_user_Following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
