# Generated by Django 3.1.1 on 2020-11-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20201115_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Followers',
        ),
    ]
