# Generated by Django 3.1.1 on 2020-11-15 20:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20201115_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Follower',
        ),
        migrations.AddField(
            model_name='user',
            name='Following',
            field=models.ManyToManyField(blank=True, default=0, related_name='_user_Following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
