# Generated by Django 3.1.1 on 2020-11-17 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20201115_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Follower',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.RemoveField(
            model_name='user',
            name='Following',
        ),
        migrations.AddField(
            model_name='user',
            name='Following',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow', to=settings.AUTH_USER_MODEL)),
                ('User_involved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
