# Generated by Django 3.1.1 on 2020-12-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_user_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(default='profile.png', upload_to='profile_pics'),
        ),
    ]
