# Generated by Django 3.1.1 on 2020-12-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20201215_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Img',
            field=models.ImageField(blank=True, upload_to='Post_img'),
        ),
    ]
